version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: backend
    command:  sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000" #Go to this url when application start over the docker : http://localhost:8000/docs
    volumes:
      - ./backend:/usr/src/app/
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      target: runner
    container_name: frontend
    volumes:
      - ./frontend:/app/
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development